---
title: "Data Science - Avocado Prices"
author: "Jens Mattsson"
date: "2020 M06 30"
output:
  pdf_document: default
  word_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###R tips and tricks

Cursor inside a command and press f1 will open the help window.
cursor inside a chunk: Run current line: ctrl+enter. Run whole chunk: ctrl+shit+enter.
When saving code and uploading to github: Git, Diff, click checkbox, write some commit command, commit, then pull, then push.
remove()


```{r Load packages and data set, echo=FALSE, include=FALSE}
packages = c("stargazer", "ggplot2", "lubridate")
lapply(packages, library, character.only = TRUE)

Avocado = read.csv("avocado.csv", header = T, sep = ",")
```



##Inspect, plot, and check descriptive statistics

```{r fix the Date variable, echo=FALSE, include=FALSE}
is.Date(Avocado$Date)
Avocado$Date = as.Date(Avocado$Date)
is.Date(Avocado$Date)
str(Avocado)
```

```{r rename variables, echo=FALSE, include=FALSE}
names(Avocado)[5] = "Small"
names(Avocado)[6] = "Large"
names(Avocado)[7] = "XL"
```


```{r echo=FALSE}
names(Avocado)
ggplot(Avocado) + geom_point(aes(y = AveragePrice, x = Date), size = 0.2) + scale_x_date(date_breaks = "1 year") + geom_smooth(aes(y = AveragePrice, x = Date))



col = colnames(Avocado)
for (i in col) {
  ggplot(Avocado) + geom_point(aes(y = AveragePrice, x = i), size = 0.2)
}
for (i in colnames(Avocado)[2][4:14]){
ggplot(Avocado) + geom_point(aes(y = AveragePrice, x = i), size = 0.2)
}
for (i in col){
plot(Avocado$AveragePrice,Avocado$i)
  }
```


```{r}
length(unique(Avocado$region))
```



